dist: xenial
language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: KTq0LQMulThUbGkln8lP55pm6KBS2JHcOfIFIwAL6FLYLl1EhztgMzhE28U7svVtL2nDDUh3C/GBZF6T2IyA8Z5D6luL3IPqX3N0up6b9HelQr/u0tvgM+5DzIj7sdIvPU3h5J/XEtJyvWcg3t+8Kxi5VcGO4hjgTk0R9JEn1D0=
  - secure: PyPfmjeLPh2cRge76dweuSCbE1Dg0z7XLe50Fb2GOP4SexYl8B/kmCFdLxad+8DC6KakMu4WlzgUTWucwI1eTDX079PeSeCCtz5a9dchk19d0Xo6H3T0vdvE5VK9ArfYOOVQ1i1KfL7kjY3Ke3MJmkRpEj8ZaiJmb3yElDyMwms=
  - secure: Q5iBxKND2/Iat3vTi0fMM/EXBpY5QYx+/TD6l1yKaTAqoMAGYZza5VPvBuvqilplbfbV1mtdsj7FS15K3X8OIGe/MPfza03YjlWH4H8oGLl4LKCBZMUgON9CheVRVIf2oylyJGi0FvR1Ib/cPlAlxNl1IrQOj55iHR1/Jifhi+Q=
  - secure: c8TxY4bgcImSSZlZxc97m6mgtjGSHyhDxpt09T7hetqqlfCfJSFOOwgWYuz28MDejGjNnEEd1IrsuzdHDJKamwgtg2ZQIPvg0n4neSZsz2LcNOBvTzlxH0wch8Nl1KNz3VHD0cCLWPWVvp1AmwgtVk7xh220ZoJ1ITePUIs7Uyc=
